[project]
name = "pii-redactor"
version = "0.1.0"
description = "PII redaction tool using spaCy NER"
dependencies = [
    "spacy>=3.8.7",
]

[project.scripts]
pii-redactor = "pii_redactor:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
